#format
format_a = "{:d}".format(52)
format_b = "{:5d}".format(52)
format_c = "{:10d}".format(52)
format_d = "{:05d}".format(52)
format_e = "{:05d}".format(-52)
print(format_a)
print(format_b)
print(format_c)
print(format_d)
print(format_e)

format_f="{:+d}".format(52)
format_g="{:+d}".format(-52)
format_h="{: d}".format(52)
format_i="{: d}".format(-52)
print(format_f)
print(format_g)
print(format_h)
print(format_i)


format_j = "{:+5d}".format(52)
format_k = "{:+5d}".format(-52)
format_l = "{:=+5d}".format(52)
format_m = "{:=+5d}".format(-52)
format_n = "{:+05d}".format(52)
format_o = "{:+05d}".format(-52)
print(format_j)
print(format_k)
print(format_l)
print(format_m)
print(format_n)
print(format_o)

output_a = "{:15.3f}".format(52.273)
output_b = "{:15.2f}".format(52.273)
output_c = "{:15.1f}".format(52.273)
print(output_a)
print(output_b)
print(output_c)